# Generated by Django 5.0.2 on 2024-07-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0002_model2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='staffid',
        ),
    ]
