# Generated by Django 5.0.2 on 2024-07-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0003_remove_model2_staffid'),
    ]

    operations = [
        migrations.CreateModel(
            name='model3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=50)),
                ('quantity', models.IntegerField(max_length=50)),
            ],
        ),
    ]
