# Generated by Django 5.0.2 on 2024-07-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0005_remove_model3_price_remove_model3_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model3',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
