# Generated by Django 5.0.2 on 2024-07-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0006_model3_price_model3_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('phoneno', models.IntegerField()),
            ],
        ),
    ]
