# Generated by Django 5.0.2 on 2024-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0007_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='phoneno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
