# Generated by Django 5.0.2 on 2024-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0008_model1_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='model1',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model1',
            name='phoneno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='model1',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
